function [Field1New,Field2New,Field3New] = SF_Adapt(varargin)
% 
% This is part of StabFem Project, version 2.1, D. Fabre, July 2017
% Generalized in July 2018, J. Sierra.
% Matlab driver for Adapting Mesh 
%
% usage : [Field1New,Field2New,Field3New] = SF_Adapt(nFields,Field1,{Field2},
%          {Field3},{TypeField1},{TypeField2},{TypeField3},{Hmax},{Hmin}
%          {rr},{Ratio},{InterpError},{Splitin2})
%
% Parameters between {} are optional
% 
%
% In the current version the user may select between 1 to 3 generic Fields
% Theu user may selected between the following types of FEM spaces
%
%   type = "ReP2P2P1" -> Real P2xP2xP1 data (for instance 2D base flow)
%   type = "CxP2P2P1" -> Complex P2xP2xP1 data (for instance 2D mode or 2D base flow with complex mapping)
%   type = "ReP2P2P2P1" -> Real P2xP2xP2xP1 data (for instance 3D base flow)
%   type = "CxP2P2P2P1" -> Complex P2xP2xP2xP1 data (for instance 3D mode or 3D base flow with complex mapping)
%   type = "ReP2P2P1P1" -> Real P2xP2xP1xP1 data (for instance 2D base flow with extra scalar)
%   type = "CxP2P2P1P1" -> Complex P2xP2xP1xP1 data (for instance 2D mode or 2D base flow with complex mapping with an extra scalar)
%   type = "ReP2P2P1P1P1" -> Real P2xP2xP1xP1xP1 data (for instance 2D compressible base flow)
%   type = "CxP2P2P1P1P1" -> Complex P2xP2xP1xP1xP1 data (for instance 2D compressible mode or 2D compressible base flow with complex mapping)
%
%
% Note: The baseflow should be included in Field1
% If baseflow is included in Field1, then the base flow will be recomputed 
% on the adapted mesh
%
%
% Version 2.2 by J. Sierra, 16 july 2018

global ff ffdir ffdatadir sfdir verbosity

% managament of optional parameters
p = inputParser;
nFields=varargin{1};
if(nFields==1)
    % input mode for adaptation to Field1
    Field1=varargin{2};
    vararginopt={varargin{3:end}};
elseif(nFields == 2)
    % input mode for adaptation to Field1,Field2
    Field1=varargin{2};
    Field2=varargin{3};
    vararginopt={varargin{4:end}};
elseif(nFields == 3)
    % input mode for adaptation to Field1,Field2
    Field1=varargin{2};
    Field2=varargin{3};
    Field3=varargin{4};
    vararginopt={varargin{5:end}};
end

addParameter(p,'Hmax',10);
addParameter(p,'Hmin',1e-4);
addParameter(p,'Ratio',10.);               	
addParameter(p,'InterpError',1e-2);			
addParameter(p,'rr',0.95);
addParameter(p,'Splitin2',0); 
addParameter(p,'typeField1','ReP2P2P1');
addParameter(p,'typeField2','None'); 
addParameter(p,'typeField3','None'); 
parse(p,vararginopt{:});
    

%%% Writing parameter file for Adapmesh
fid = fopen('Param_Adaptmesh.edp','w');
fprintf(fid,'// Parameters for adaptmesh (file generated by matlab driver)\n');
fprintf(fid,['real Hmax = ',num2str(p.Results.Hmax),' ;']);
fprintf(fid,['real Hmin = ',num2str(p.Results.Hmin),' ;']);
fprintf(fid,['real Ratio = ',num2str(p.Results.Ratio),' ;']);
fprintf(fid,['real error = ',num2str(p.Results.InterpError),' ;']);
 fprintf(fid,['real rr = ',num2str(p.Results.rr),' ;']);
if(p.Results.Splitin2==0)
    fprintf(fid,['bool Splitin2 = false ;']);
else
    fprintf(fid,['bool Splitin2 = true ;']);
end
fclose(fid);

disp(' '); 

% Copy Field files to Fieldi_toadapt
mycp([Field1.filename],[ffdatadir 'Field0_toadapt.txt']);
if(nFields == 3)
    mycp([Field2.filename],[ffdatadir 'Field1_toadapt.txt']);
    mycp([Field3.filename],[ffdatadir 'Field2_toadapt.txt']);
elseif(nFields == 2)
    mycp([Field2.filename],[ffdatadir 'Field1_toadapt.txt']);
else
    mycp([Field1.filename],[ffdatadir 'Field1_toadapt.txt']);
    mycp([Field1.filename],[ffdatadir 'Field2_toadapt.txt']);
    disp('Only a field is chosen for mesh adaptation');
end
mycp([ffdatadir 'mesh.msh'],[ffdatadir 'mesh_toadapt.msh']);

% Command to call FreeFem to adapt the Fields
command = ['echo ',p.Results.typeField1,' ',p.Results.typeField2,' ',...
           p.Results.typeField3,' ','| ',ff,' ',ffdir,'Adapt_Mode.edp']; 
error = 'ERROR : FreeFem adaptmesh aborted';
% Launch FreeFem
mysystem(command,error);

% Copy interpolated files to the original paths
mycp([ffdatadir 'mesh_adapted.msh'],[ffdatadir 'mesh.msh']);
mycp([ffdatadir 'mesh_adapted.ff2m'],[ffdatadir 'mesh.ff2m']);
mycp([ffdatadir 'Field0_adapted.txt'],[Field1.filename]);
if(nFields == 3)
    mycp([ffdatadir 'Field1_adapted.txt'],[Field2.filename]);
    mycp([ffdatadir 'Field2_adapted.txt'],[Field3.filename]);
elseif(nFields == 2)
    mycp([ffdatadir 'Field1_adapted.txt'],[Field2.filename]);
end

meshnp = importFFmesh('mesh.msh','nponly');
disp(['      ### ADAPT mesh to input fields ' ...% for Re = ' num2str(baseflow.Re)... 
      ' ; InterpError = ' num2str(p.Results.InterpError) '  ; Hmax = ' num2str(p.Results.Hmax) ])  

% Field1 in  the new mesh
Field1New = Field1;
Field1New.mesh=importFFmesh([ffdatadir 'mesh.msh']);

%Copy Fieldi to guess and set Fieldi new mesh
if(nFields == 3)
    mycp([ffdatadir 'Field1_adapted.txt'],[ffdatadir Field2.datatype '_guess.txt']);
    Field2New = Field2;
    Field2New.mesh=importFFmesh([ffdatadir 'mesh.msh']);
    mycp([ffdatadir 'Field2_adapted.txt'],[ffdatadir Field3.datatype '_guess.txt']);
    Field3New = Field3;
    Field3New.mesh=importFFmesh([ffdatadir 'mesh.msh']);
elseif(nFields == 2)
    mycp([ffdatadir 'Field1_adapted.txt'],[ffdatadir Field2.datatype '_guess.txt']);
    Field2New = Field2;
    Field2New.mesh=importFFmesh([ffdatadir 'mesh.msh']);
end

if(verbosity>=1)
  meshinfo = importFFdata(Field1New.mesh,'mesh.ff2m');
  disp(['      #   Number of points np = ',num2str(meshinfo.np), ...
        ' ; Ndof = ', num2str(meshinfo.Ndof)]);
  disp(['      #  h_min, h_max : ',num2str(meshinfo.deltamin), ' , ',...
        num2str(meshinfo.deltamax)]);    
end
   
    % recomputing base flow after adapt
    if(Field1.datatype == 'BaseFlow')
        mycp([ffdatadir 'Field0_adapted.txt'],[ffdatadir 'BaseFlow_guess.txt']);
        Field1New = SF_BaseFlow(Field1New,'Re',Field1.Re,'type','NEW');
        if(Field1New.iter>0)
            %  Newton successful : store base flow
            Field1New.mesh.namefile=[ffdatadir 'BASEFLOWS/mesh_adapt_Re' num2str(Field1.Re) '.msh'];
            mycp([ffdatadir 'BaseFlow.txt'],[ffdatadir 'BASEFLOWS/BaseFlow_adapt_Re' num2str(Field1New.Re) '.txt']);
            Field1.namefile = [ ffdatadir 'BASEFLOWS/BaseFlow_Re' num2str(Field1New.Re) '.txt'];
            mycp([ffdatadir 'mesh.msh'],[ffdatadir 'BASEFLOWS/mesh_adapt_Re' num2str(Field1New.Re) '.msh']);
             % clean 'BASEFLOWS' directory to avoid mesh/baseflow incompatibilities
             myrm([ffdatadir 'BASEFLOWS/BaseFlow_Re*']);
             mycp([ffdatadir 'BaseFlow.txt'],[ffdatadir 'BASEFLOWS/BaseFlow_Re' num2str(Field1New.Re) '.txt']);
             mycp([ffdatadir 'BaseFlow.ff2m'],[ffdatadir 'BASEFLOWS/BaseFlow_Re' num2str(Field1New.Re) '.ff2m']);

        else % Newton has probably diverged : revert to previous mesh/baseflow
            mymv([ffdatadir 'mesh_ans.msh'],[ffdatadir 'mesh.msh']);
            mymv([ffdatadir 'BaseFlow_ans.txt'],[ffdatadir 'BaseFlow_guess.txt']);
            error(' ERROR in SF_Adapt : recomputing base flow failed, going back to baseflow/mesh') 
        end
    else
        if(Field1.datatype == 'EigenmodeD' || Field1.datatype == 'EigenmodeA')
            disp('Eigenmode fields are not set to guess');
        else
            mycp([ffdatadir 'Field0_adapted.txt'],[ffdatadir Field0.datatype '_guess.txt']);
        end
    end
    
    % Delete temporal files
    myrm([ffdatadir '*_ans.* ']);
    myrm([ffdatadir '*_toadapt.* ']);
    myrm([ffdatadir '*_adapted.* ']);
end
