function myWriteMethod(CM,mesh,method)
    xinfm=mesh.xinfm;
    xinfv=mesh.xinfv;
    yinf=mesh.yinf;

    alpha=method.alpha;
    name = method.name;
    symm=method.symm;
    symmEig=method.symmEig;
    BoxXpCoeff = CM.BoxXpCoeff;
    BoxXnCoeff = CM.BoxXnCoeff;
    BoxYpCoeff = CM.BoxYpCoeff;
    LaXpCoeff =  CM.LaXpCoeff;
    LaXnCoeff =  CM.LaXnCoeff;
    LaYpCoeff =  CM.LaYpCoeff;
    LcXpCoeff =  CM.LcXpCoeff;
    LcXnCoeff =  CM.LcXnCoeff;
    LcYpCoeff =  CM.LcYpCoeff;
    gcXpCoeff =  CM.gcXpCoeff;
    gcXnCoeff =  CM.gcXnCoeff;
    gcYpCoeff =  CM.gcYpCoeff;

    mysystem(['echo "xinfm= ' num2str(xinfm) '; xinfv= ' num2str(xinfv) ...
          '; yinf= ' num2str(yinf) ';" > SF_Mesh.edp']); 
    mysystem(['echo "alpha= ' num2str(alpha) '; method= \"' name ...
    '\"; symmetryBaseFlow= ' num2str(symm)...
    '; symmetryEigenmode= ' num2str(symmEig) ... 
    '; BoxXpCoeff= ' num2str(BoxXpCoeff) ... 
    '; BoxXnCoeff= ' num2str(BoxXnCoeff) ... 
    '; BoxYpCoeff= ' num2str(BoxYpCoeff) ... 
    '; LaXpCoeff= ' num2str(LaXpCoeff) ... 
    '; LaXnCoeff= ' num2str(LaXnCoeff) ... 
    '; LaYpCoeff= ' num2str(LaYpCoeff) ... 
    '; LcXpCoeff= ' num2str(LcXpCoeff) ... 
    '; LcXnCoeff= ' num2str(LcXnCoeff) ... 
    '; LcYpCoeff= ' num2str(LcYpCoeff) ... 
    '; gcXpCoeff= ' num2str(gcXpCoeff) ... 
    '; gcXnCoeff= ' num2str(gcXnCoeff) ... 
    '; gcYpCoeff= ' num2str(gcYpCoeff) ';" > SF_Method.edp']);
    
    disp('It has been written SF_Method, SF_Geom, SF_Mesh');
end