==> BaseFlow.ff2m <==
### Data generated by Freefem++ ; 
Temperature field in a L-shaped region ; steady conduction with constant volume source
Format : 
P1 T

1.21744e-63
1.27234e-33
1.16254e-33
2.04199e-33
1.85851e-33
0.0012313
0.00155321
0.00165368
2.72134e-33
2.72331e-33
0.00266376
0.00354042
0.00314448
0.00194664
3.25487e-33

==> Data.ff2m <==
### Data generated by Freefem++ ; 
Temperature field in a L-shaped region ; steady conduction with constant volume source
Format : 
P1 T

1.21744e-63
1.27234e-33
1.16254e-33
2.04199e-33
1.85851e-33
0.0012313
0.00155321
0.00165368
2.72134e-33
2.72331e-33
0.00266376
0.00354042
0.00314448
0.00194664
3.25487e-33

==> DataFile.ff2m <==
### Data generated by Freefem++ ; 
Temperature field in a L-shaped region ; steady conduction with constant volume source
Format : 
P1 T

1.21744e-63
1.27234e-33
1.16254e-33
2.04199e-33
1.85851e-33
0.0012313
0.00155321
0.00165368
2.72134e-33
2.72331e-33
0.00266376
0.00354042
0.00314448
0.00194664
3.25487e-33

==> Heat_1Dcut.ff2m <==
### Data generated by Freefem++ ; 
Temperature field in a L-shaped region ; values along a transverse line
Format : 
real.101 Xcut  real.101 Tcut

0
0.01
0.02
0.03
0.04
0.05
0.06
0.07
0.08
0.09
0.1
0.11
0.12
0.13
0.14

==> Heat_unsteady.ff2m <==
### Data generated by Freefem++ ; 
Temperature field in a L-shaped region ; UNsteady conduction with harmonic forcing at boundaries
Format : 
real omega P1c Tc P1 normTc

10
1 5.20833e-34
1 1.40445e-32
1 1.3607e-32
1 2.12215e-32
1 1.96862e-32
0.998836 0.01208
0.998464 0.0152236
0.998238 0.0161799
1 2.77033e-32
1 2.81179e-32
0.997041 0.0260394
0.99591 0.0345744
0.99634 0.0306991
0.997727 0.0190004

==> SF_Init.ff2m <==
Defininition of problem type and geometry for StabFem. Problem type : 
EXAMPLE
Format :  (this list may contain geometrical parameters such as domain dimensions, etc..)
real R 
1

==> files.ff2m <==
==> BaseFlow.ff2m <==
### Data generated by Freefem++ ; 
Temperature field in a L-shaped region ; steady conduction with constant volume source
Format : 
P1 T

1.21744e-63
1.27234e-33
1.16254e-33
2.04199e-33
1.85851e-33
0.0012313
0.00155321
0.00165368
2.72134e-33
2.72331e-33
0.00266376
0.00354042
0.00314448
0.00194664

==> mesh.ff2m <==
Mesh generated by FreeFem++ ; mesh type :
2D
Format : 
int np int nt int density
1426 2690 40
